### ISSUE TITLE
improving user convenience -reg

### ISSUE THREAD

**Issue by krissh-codes** [VarthanV/powerboil#1]
https://github.com/VarthanV/powerboil/blob/e205b9626bb7177813707ea93c2dde242c50e54a/powerboil.py#L240
-
here, use replace(" ", "_") method and just notify the user, so that they won't have to type in the name without spaces again. If they don't want underscores, they can change it manually. mostly they'll use underscores only.
hope that makes sense. Good luck. Your project is cool ;)

**Comment by VarthanV** [comment]
Thanks Krishna for your concern what this does is if the user presses Return without entering a valid name it jumps to the loop thats the logic up here

**Comment by krissh-codes** [comment]
Hmmm... We have to find a way out. Maybe if yourVar == '\n' can do it? 

_Sent from my ZenFone Max Pro M1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by VarthanV** [comment]
Sure let's make it commit ur changes
